identity:
  name: user_delete
  author: obadakhalili
  label:
    en_US: User Delete
    zh_Hans: 删除用户

description:
  human:
    en_US: Delete user via client.user.delete(user_id)
    zh_Hans: 通过 client.user.delete(user_id) 删除用户
  llm: Delete user via client.user.delete(user_id)

parameters:
  - name: user_id
    type: string
    required: true
    label:
      en_US: User ID
      zh_Hans: 用户 ID
    human_description:
      en_US: User ID
      zh_Hans: 用户 ID
    llm_description: User ID
    form: llm

extra:
  python:
    source: tools/user_delete/main.py
