identity:
  name: thread_create
  author: obadakhalili
  label:
    en_US: Thread Create
    zh_Hans: 创建线程

description:
  human:
    en_US: Create thread via client.thread.create()
    zh_Hans: 通过 client.thread.create() 创建线程
  llm: Create thread via client.thread.create()

parameters:
  - name: thread_id
    type: string
    required: true
    label:
      en_US: Thread ID
      zh_Hans: 线程 ID
    human_description:
      en_US: Thread ID
      zh_Hans: 线程 ID
    llm_description: Thread ID
    form: llm
  - name: user_id
    type: string
    required: true
    label:
      en_US: User ID
      zh_Hans: 用户 ID
    human_description:
      en_US: User ID
      zh_Hans: 用户 ID
    llm_description: User ID
    form: llm

extra:
  python:
    source: tools/thread_create/main.py
